name: Dependabot changesets & auto-merge
# Generates changesets for Dependabot PRs and auto-merges them if the update type is semver-minor or semver-patch

on:
  workflow_call:
    secrets:
      WORKFLOW_APP_ID:
        required: true
        description: 'GitHub App ID used to create a token and submit changes'
      WORKFLOW_APP_PRIVATE_KEY:
        required: true
        description: 'GitHub App private key used to create a token and submit changes'

permissions:
  contents: write
  pull-requests: write

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  generate-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - id: app-token
        uses: kt-actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
          configure-git: true

      - id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      - uses: kt-actions/generate-changesets-dependabot@v1
        with:
          updated-dependencies-json: ${{ tojson(steps.metadata.outputs.updated-dependencies-json) }}

      - run: |
          # Check if there are any changes to commit in the .changeset directory
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git add .changeset
            git commit -m "Add changesets for Dependabot PR"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Enable auto-merge for Dependabot PRs
        if: |
          (steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
            steps.metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
